language: python
python: 2.7
env:
  - TOX_ENV=py27-lint
  - TOX_ENV=py34-lint
  - TOX_ENV=py27-lint-readme
  - TOX_ENV=py26
  - TOX_ENV=py27

install:
  - pip install tox coveralls

script: tox -e $TOX_ENV

after_success:
  - coveralls
